If you want to read a journal that you do not have the access to, send an email to kc.linguistics@gmail.com, do not use the DOI of an article and paste it on https://sci-hub.mksa.top/ to get it for free, you will get blocked eventually. Please do not use proton vpn to mask your id so that you can gain your access back.

1. [Sciendo](https://sciendo.com/subject/LS)
1. [Lingbuzz](https://ling.auf.net/lingbuzz)
1. [Semantic Scholar](https://www.semanticscholar.org/?utm_source=google&utm_medium=cpc&utm_campaign=search_br_world_wq&utm_content=&utm_term=semantic%20scholar%20org&gclid=CjwKCAjw-ZCKBhBkEiwAM4qfF_rpxP0VQ7z89WhphToj5hZEhcPz4a5ACMgRt5R8wWfM9P5wphs8xxoCXiMQAvD_BwE)
1. [Glossa Journal](https://www.glossa-journal.org/)
1. [Leibniz-zas.de](https://www.leibniz-zas.de/en/about-us/institute)
1. [Wiley.com](https://onlinelibrary.wiley.com/journal/14679612)
1. [Springer](https://www.springer.com/journal/11049)
1. [Frontiersin](https://www.frontiersin.org/journals/psychology)
1. [Nature](https://www.nature.com/nrn/)
1. [TandfOnline](https://www.tandfonline.com/toc/hdsp20/current)
1. [Wiley.com II](https://onlinelibrary.wiley.com/journal/14682885)
1. [SagePub](https://journals.sagepub.com/home/jls)
1. [TandfOnline](https://www.tandfonline.com/toc/hmet20/current)
1. [Elsevier](https://www.journals.elsevier.com/cortex)
1. [Asha](https://pubs.asha.org/journal/jslhr)
1. [Pragmatics](https://www.journals.elsevier.com/journal-of-pragmatics)
1. [Cambridge](https://www.cambridge.org/core/journals/english-language-and-linguistics)
1. [Benjamins](https://benjamins.com/catalog/ijcl)
1. [Wiley.com III](https://onlinelibrary.wiley.com/journal/14680017)
1. [Lingua](https://www.journals.elsevier.com/lingua)
1. [Benjamins/catalogue - jpcl](https://benjamins.com/catalog/jpcl)
1. [Benjamins/catalogue - jhl](https://benjamins.com/catalog/jhl)
1. [Benjamins/ catalogue - dia](https://benjamins.com/catalog/dia)
1. [DeGruyter](https://www.degruyter.com/journal/key/lity/html)
1. [Springer II](https://www.springer.com/journal/11525)
1. [Elsevier/ Journal of Phonetics](https://www.journals.elsevier.com/journal-of-phonetics)
1. [Elsevier/ Discourse Context and Media](https://www.journals.elsevier.com/discourse-context-and-media)
1. [Syntax Must Reads](https://docs.google.com/spreadsheets/u/0/d/1pkID14V7CZ4_5kDg3r_fx63y1ca8EgbrLrnMJG3TmjY/htmlview?s=08)

